FROM amazon/aws-lambda-python:3.12

# Install chrome dependencies
RUN dnf install -y atk cups-libs gtk3 libXcomposite alsa-lib \
    libXcursor libXdamage libXext libXi libXrandr libXScrnSaver \
    libXtst pango at-spi2-atk libXt xorg-x11-server-Xvfb \
    xorg-x11-xauth dbus-glib dbus-glib-devel nss mesa-libgbm jq unzip
    
# Copy and run the chrome installer script
COPY Dockerfiles/chrome-installer.sh .
RUN chmod +x ./chrome-installer.sh
RUN ./chrome-installer.sh
RUN rm ./chrome-installer.sh

RUN pip install selenium
RUN pip install awswrangler

COPY modules/bgg_boardgame_file_retrieval/get_bgg_games_file.py .
COPY config* .
COPY utils utils

CMD [ "get_bgg_games_file.lambda_handler" ]
