FROM python:3.12-slim

# Install required dependencies
RUN apt-get update && apt-get install -y \
    python3-pip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set up environment variables
ARG END_BLOCK
ENV END_BLOCK=$END_BLOCK

ARG START_BLOCK
ENV START_BLOCK=$START_BLOCK

# Install pipenv
RUN pip3 install pipenv

# Set PYTHONPATH to the current directory
ENV PYTHONPATH=.

# Copy the source code into the container
COPY modules/rag_description_generation modules/rag_description_generation
COPY utils utils
COPY modules/rag_description_generation/Pipfile* .
COPY config* .
COPY nltk_data root/nltk_data

# Install dependencies with pipenv
RUN pipenv sync

# Set the entry point and command
ENTRYPOINT ["pipenv", "run", "python", "modules/rag_description_generation/main.py"]
CMD ["$START_BLOCK", "$END_BLOCK"]