FROM python:3.12-slim

# Install required dependencies
RUN apt-get update && apt-get install -y \
    python3-pip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install pipenv
RUN pip3 install pipenv

# Create necessary directories
RUN mkdir -p modules 

# Set PYTHONPATH to the current directory
ENV PYTHONPATH=.

# Copy the source code into the container
COPY modules/bgg_dynamodb_data_store modules/bgg_dynamodb_data_store
COPY utils utils
COPY modules/bgg_dynamodb_data_store/Pipfile* .
COPY config* .

# Install dependencies with pipenv
RUN pipenv sync

ENTRYPOINT ["pipenv", "run", "python", "modules/bgg_dynamodb_data_store/main.py"]