FROM python:3.12-slim

# Install required dependencies
RUN apt-get update && apt-get install -y \
    python3-pip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set up environment variables
ARG END_BLOCK
ENV END_BLOCK=$END_BLOCK

ARG START_BLOCK
ENV START_BLOCK=$START_BLOCK

# Install pipenv
RUN pip3 install pipenv

# Copy the source code into the container
COPY modules/rag_description_generation modules/rag_description_generation
COPY utils utils
COPY modules/rag_description_generation/Pipfile* .
COPY config.py .

# Install dependencies with pipenv
RUN pipenv sync

# Temporarily install nltk to download resources
RUN pip3 install nltk

# Set NLTK_DATA environment variable
ENV NLTK_DATA /usr/share/nltk_data

# Set NLTK_DATA environment variable
RUN python3 -m nltk.downloader stopwords -d /usr/share/nltk_data
RUN python3 -m nltk.downloader punkt -d /usr/share/nltk_data

# Set the entry point and command
ENTRYPOINT ["pipenv", "run", "python", "modules/rag_description_generation/main.py"]
CMD ["$START_BLOCK", "$END_BLOCK"]
