name: Lambda Trigger PROD CICD Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Zip functions
        run: |
          cd lambda_functions
          zip -r boardgame_scraper_fargate_trigger.zip boardgame_scraper_fargate_trigger.py ../config.py ../utils
          zip -r boardgame_cleaner_fargate_trigger.zip boardgame_cleaner_fargate_trigger.py ../config.py ../utils
          zip -r generate_game_urls_lambda.zip generate_game_urls_lambda.py ../config.py ../utils
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE }}
          aws-region: us-west-2
      - run: |
          cd lambda_functions
          aws lambda update-function-code --function-name=bgg_generate_game_urls  --zip-file=fileb://generate_game_urls_lambda.zip 
          aws lambda update-function-code --function-name=boardgame_scraper_fargate_trigger  --zip-file=fileb://boardgame_scraper_fargate_trigger.zip
          aws lambda update-function-code --function-name=boardgame_cleaner_fargate_trigger  --zip-file=fileb://boardgame_cleaner_fargate_trigger.zip
          aws lambda update-function-code --function-name=bgg_generate_user_urls  --zip-file=fileb://generate_user_urls_lambda.zip
