name: Lambda Trigger PROD CICD Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Zip functions
        run: |
          cd lambda_functions
          zip -r bgg_scraper_fargate_trigger.zip bgg_scraper_fargate_trigger.py ../config.py ../utils
          zip -r bgg_generate_urls_lambda.zip bgg_generate_urls_lambda.py ../config.py ../utils
          zip -r bgg_orchestrator_fargate_trigger.zip bgg_orchestrator_fargate_trigger.py ../config.py ../utils
          zip -r bgg_data_cleaner_fargate_trigger.zip bgg_data_cleaner_fargate_trigger.py ../config.py ../utils
          zip -r rag_description_generation_fargate_trigger.zip rag_description_generation_fargate_trigger.py ../config.py ../utils
          zip -r bgg_xml_cleanup_fargate_trigger.zip bgg_xml_cleanup_fargate_trigger.py ../config.py ../utils
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Post Lambda Functions
        run: |
          cd lambda_functions
          aws lambda update-function-code --function-name=bgg_scraper_fargate_trigger  --zip-file=fileb://bgg_scraper_fargate_trigger.zip > /dev/null 2>&1
          aws lambda update-function-code --function-name=bgg_generate_urls_lambda  --zip-file=fileb://bgg_generate_urls_lambda.zip > /dev/null 2>&1
          aws lambda update-function-code --function-name=bgg_orchestrator_fargate_trigger  --zip-file=fileb://bgg_orchestrator_fargate_trigger.zip > /dev/null 2>&1
          aws lambda update-function-code --function-name=bgg_data_cleaner_fargate_trigger  --zip-file=fileb://bgg_data_cleaner_fargate_trigger.zip > /dev/null 2>&1
          aws lambda update-function-code --function-name=rag_description_generation_fargate_trigger  --zip-file=fileb://rag_description_generation_fargate_trigger.zip > /dev/null 2>&1
          aws lambda update-function-code --function-name=bgg_xml_cleanup_fargate_trigger  --zip-file=fileb://bgg_xml_cleanup_fargate_trigger.zip > /dev/null 2>&1
